hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/cdg_hyd_jfs_049
hibernate.connection.username=root
hibernate.connection.password=root
hibernate.show_sql=true