
#spring.mvc.servlet.path=/javawebapp04062026

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.thymeleaf.view-names=*.html
spring.thymeleaf.prefix=classpath:/static/


spring.datasource.url=jdbc:mysql://localhost:3306/cdg_hyd_jfs_049
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jsp.show-sql=true